version: "3.8"

services:
  # Servicio de la aplicación Node.js
  app_localizabaño:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: localizabaño_app # Nombre de contenedor predecible
    restart: always
    env_file: ./.env.prod
    depends_on:
      - postgres_db_localizabaño
    networks:
      - default # Red interna para comunicarse con la BD
      - nginx_proxy_manager_network # Red externa para comunicarse con el proxy

  # Servicio de la Base de Datos PostGIS
  postgres_db_localizabaño:
    image: postgis/postgis:14-3.3
    container_name: localizabaño_db
    restart: always
    env_file: ./.env.prod
    volumes:
      - postgres_localizabaño_data:/var/lib/postgresql/data
    networks:
      - default # Solo necesita estar en la red interna

volumes:
  postgres_localizabaño_data: # Volumen de datos único para esta app

networks:
  nginx_proxy_manager_network:
    external: true # ¡Clave! Le dice a Docker que esta red ya existe.
    name: nombre_de_la_red_del_proxy # <-- REEMPLAZARÁS ESTO
